# Travis-CI Build for rabbitmq-c
# see travis-ci.org for details

language: c

# Use the faster container-based infrastructure.
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gDwqo3jHj+HHGzFKnxL/nwZhbVeh2pItw0TbeaHcLtWubUZaf85ViEQRaXPyfnbG7l0OEQq+PjyhKAfvViVq2NP0lGeeu4VM5uMZJhsCLN594BJr39Y4XzOapg0O8mEMhQ0DU2u1Zo4LMgEcRz67aosVQOj6QV30tOzp9fnxn9U="

matrix:
  include:
    - compiler: gcc
      os: linux
      env: CONFIG=autotools
    - compiler: gcc
      os: linux
      env: CONFIG=cmake
    - compiler: clang
      os: linux
      env: CONFIG=cmake
    - compiler: clang
      os: linux
      env: CONFIG=asan
    - compiler: clang
      os: linux
      env: CONFIG=tsan
    - compiler: clang
      os: osx
      env: CONFIG=cmake

# Run the Build script
script:
  - ./travis.sh $CONFIG

addons:
  apt:
    packages:
      - libpopt-dev

  coverity_scan:
    project:
      name: "alanxz/rabbitmq-c"
      description: "C AMQP client for RabbitMQ"
    notification_email: alan.antonuk@gmail.com
    build_command_prepend: cmake ..
    build_command: cmake --build .
    branch_pattern: coverity_scan
